// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChat.Presistence.DBContext;

#nullable disable

namespace WebChat.Infrastructure.MySQL.Migrations
{
    [DbContext(typeof(WebchatDBContext))]
    [Migration("20240223134407_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebChat.Domain.Entities.GroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UtcDateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UtcDateModified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "Win",
                            RowId = new Guid("d8a523e8-8161-4c0a-ba1e-af3fad824870"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8498)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "5D",
                            RowId = new Guid("0fad54b4-cc04-40d4-a936-cdfe5690eb2c"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8504)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "K3",
                            RowId = new Guid("5de3e552-080a-45c7-97f0-381968cd0c91"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8505)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "TrxWin",
                            RowId = new Guid("4024040a-753d-42d5-ab49-9771def77c52"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8506)
                        });
                });

            modelBuilder.Entity("WebChat.Domain.Entities.GroupUsersEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("char(36)");

                    b.Property<long>("SubGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UtcDateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UtcDateModified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubGroupId");

                    b.ToTable("GroupUsers");
                });

            modelBuilder.Entity("WebChat.Domain.Entities.LoginInUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UtcDateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UtcDateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UtcLastLoginTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LoginInUser");
                });

            modelBuilder.Entity("WebChat.Domain.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("SubGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("UUID")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UtcDateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UtcDateModified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SubGroupId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "Hello Team!",
                            IsActive = true,
                            RowId = new Guid("0790aeff-efbb-4b0c-ae33-b4f21549cb92"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8618),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8635)
                        },
                        new
                        {
                            Id = 2L,
                            Content = "Did you watch the recent cricket match?",
                            IsActive = true,
                            RowId = new Guid("aa82b09b-f3e3-401b-9be4-d95ac9f2bc66"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8637),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8638)
                        },
                        new
                        {
                            Id = 3L,
                            Content = "Yes, it was an exciting game!",
                            IsActive = true,
                            RowId = new Guid("c47fa05d-d053-4a6b-8abc-415027824b94"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8639),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8640)
                        },
                        new
                        {
                            Id = 4L,
                            Content = "Who do you think will win the upcoming elections?",
                            IsActive = true,
                            RowId = new Guid("20f31d9a-00d7-4e84-99dc-15079cc1644f"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8640),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8641)
                        },
                        new
                        {
                            Id = 5L,
                            Content = "I'm not sure, it's hard to predict.",
                            IsActive = true,
                            RowId = new Guid("dcc5adfb-8af3-49e5-b5ea-a00408523b81"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8642),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8642)
                        },
                        new
                        {
                            Id = 6L,
                            Content = "I think the cricket team needs better bowling.",
                            IsActive = true,
                            RowId = new Guid("94bb8d82-7b24-40ab-97c6-598ec2d882e0"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8643),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8644)
                        },
                        new
                        {
                            Id = 7L,
                            Content = "What's your favorite cricket team?",
                            IsActive = true,
                            RowId = new Guid("61d411da-c483-4131-b513-177be9479c76"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8644),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8645)
                        },
                        new
                        {
                            Id = 8L,
                            Content = "I support the national team!",
                            IsActive = true,
                            RowId = new Guid("1fe24a15-fea6-47c6-965b-9fa93ce749b8"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8646),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8646)
                        },
                        new
                        {
                            Id = 9L,
                            Content = "Cricket is so popular, isn't it?",
                            IsActive = true,
                            RowId = new Guid("4a46d8ae-a6e8-424a-ba7b-babfe2c13322"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8647),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8649)
                        },
                        new
                        {
                            Id = 10L,
                            Content = "I heard there's a new political party forming.",
                            IsActive = true,
                            RowId = new Guid("3c582416-d577-4586-8027-46ca041f0b77"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8650),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8651)
                        },
                        new
                        {
                            Id = 11L,
                            Content = "Really? What's their agenda?",
                            IsActive = true,
                            RowId = new Guid("a59ec23a-1493-4a21-815c-21758b62ecde"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8651),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8652)
                        },
                        new
                        {
                            Id = 12L,
                            Content = "I hope they focus on education and healthcare.",
                            IsActive = true,
                            RowId = new Guid("225d1ecc-e177-41da-8b9c-0a2d4735bc66"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8653),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8653)
                        },
                        new
                        {
                            Id = 13L,
                            Content = "Have you ever been to a live cricket match?",
                            IsActive = true,
                            RowId = new Guid("6420c2ef-faeb-496f-b943-5e80d9f51cc7"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8654),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8655)
                        },
                        new
                        {
                            Id = 14L,
                            Content = "Yes, the atmosphere is incredible!",
                            IsActive = true,
                            RowId = new Guid("dd337ddc-d497-4bcf-9635-74814f550e1f"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8656),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8656)
                        },
                        new
                        {
                            Id = 15L,
                            Content = "Let's plan a movie night this weekend.",
                            IsActive = true,
                            RowId = new Guid("4309fa89-a1d2-48a6-babb-5c7de7086668"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8657),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8658)
                        },
                        new
                        {
                            Id = 16L,
                            Content = "Sure, I'm up for it!",
                            IsActive = true,
                            RowId = new Guid("4063318d-4e4c-46a4-b7d9-00a49dd68c71"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8658),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8659)
                        },
                        new
                        {
                            Id = 17L,
                            Content = "I'll bring the popcorn!",
                            IsActive = true,
                            RowId = new Guid("a9df9fb9-77a8-4ab2-a8b7-9063f7ab6a91"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8660),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8662)
                        },
                        new
                        {
                            Id = 18L,
                            Content = "What's your take on the current economic situation?",
                            IsActive = true,
                            RowId = new Guid("5cac8b46-2598-4ca3-b61c-b911f1cf4560"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8662),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8663)
                        },
                        new
                        {
                            Id = 19L,
                            Content = "It's quite challenging, especially for small businesses.",
                            IsActive = true,
                            RowId = new Guid("76d7bcae-9cad-4174-b5fd-d7568c1532ef"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8664),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8664)
                        },
                        new
                        {
                            Id = 20L,
                            Content = "We should stay positive and support local businesses.",
                            IsActive = true,
                            RowId = new Guid("bc167d2a-487f-439b-8d25-b14d24980130"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8665),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8665)
                        },
                        new
                        {
                            Id = 21L,
                            Content = "What's your favorite cuisine?",
                            IsActive = true,
                            RowId = new Guid("57e04f9f-b4a8-4c4a-896a-929bc21ec4c8"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8666),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8667)
                        },
                        new
                        {
                            Id = 22L,
                            Content = "I love Italian food!",
                            IsActive = true,
                            RowId = new Guid("d265b175-79d7-410a-9b2f-4f134dc4f085"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8668),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8668)
                        },
                        new
                        {
                            Id = 23L,
                            Content = "Mexican cuisine is my go-to choice.",
                            IsActive = true,
                            RowId = new Guid("60e2769f-77cd-4840-99ca-58e7a5bb96f0"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8669),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8669)
                        },
                        new
                        {
                            Id = 24L,
                            Content = "Let's plan a potluck dinner!",
                            IsActive = true,
                            RowId = new Guid("e33dcc66-03e2-45b9-aa69-585f0b591bdc"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8670),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8671)
                        },
                        new
                        {
                            Id = 25L,
                            Content = "I'm in! I'll bring my famous lasagna.",
                            IsActive = true,
                            RowId = new Guid("4d23f3d6-55dc-4e91-80c8-95515eef5e59"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8671),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8673)
                        },
                        new
                        {
                            Id = 26L,
                            Content = "Sounds delicious! I'll make guacamole.",
                            IsActive = true,
                            RowId = new Guid("3118ddd6-6018-4b53-860d-b1966eea07b0"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8674),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8675)
                        },
                        new
                        {
                            Id = 27L,
                            Content = "Count me in too! I'll bring dessert.",
                            IsActive = true,
                            RowId = new Guid("80b91ea7-0290-4cf2-bf5c-2b439fafe33d"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8676),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8676)
                        },
                        new
                        {
                            Id = 28L,
                            Content = "Have you read any good books lately?",
                            IsActive = true,
                            RowId = new Guid("762e57a1-0c11-4841-8c30-07a3c51b724b"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8677),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8678)
                        },
                        new
                        {
                            Id = 29L,
                            Content = "I just finished a fantastic mystery novel.",
                            IsActive = true,
                            RowId = new Guid("0dc1e2f7-3451-41ae-a60d-d61caf417296"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8678),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8679)
                        },
                        new
                        {
                            Id = 30L,
                            Content = "I'm into science fiction. Any recommendations?",
                            IsActive = true,
                            RowId = new Guid("d72a8c05-4a66-46a7-b418-661eafccc8cc"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8680),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8680)
                        },
                        new
                        {
                            Id = 31L,
                            Content = "Let's organize a hiking trip next month.",
                            IsActive = true,
                            RowId = new Guid("bf9d141c-f1f4-4b5a-bf89-b8e6d4a4ab17"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8681),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8682)
                        },
                        new
                        {
                            Id = 32L,
                            Content = "That sounds like a great idea! I'm in!",
                            IsActive = true,
                            RowId = new Guid("68ba6cad-5bdb-45da-a9e9-b35e7ca3bf73"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8682),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8683)
                        },
                        new
                        {
                            Id = 33L,
                            Content = "Count me in too! I love nature hikes.",
                            IsActive = true,
                            RowId = new Guid("9ac6eece-5510-4283-803a-98e3132d0256"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8684),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8686)
                        },
                        new
                        {
                            Id = 34L,
                            Content = "What's your favorite hiking trail?",
                            IsActive = true,
                            RowId = new Guid("26618f96-514b-4e42-aad1-90e91f598ee4"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8686),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8687)
                        },
                        new
                        {
                            Id = 35L,
                            Content = "I enjoy trails with scenic views and waterfalls.",
                            IsActive = true,
                            RowId = new Guid("d5b2fb7a-da0f-493f-8aa3-75f76bd496b8"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8688),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8688)
                        },
                        new
                        {
                            Id = 36L,
                            Content = "I prefer challenging mountain trails. The more difficult, the better!",
                            IsActive = true,
                            RowId = new Guid("0df5e2d0-5c8a-4b8b-9487-37facf8e2c65"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8689),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8690)
                        },
                        new
                        {
                            Id = 37L,
                            Content = "Have you tried rock climbing before?",
                            IsActive = true,
                            RowId = new Guid("7f428405-9cea-4882-8652-7206fd09dd28"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8690),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8691)
                        },
                        new
                        {
                            Id = 38L,
                            Content = "Yes, it's an adrenaline rush! Highly recommend it.",
                            IsActive = true,
                            RowId = new Guid("4f225900-bcb2-4a74-b915-8c16374b0aa3"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8692),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8692)
                        },
                        new
                        {
                            Id = 39L,
                            Content = "Rock climbing sounds exciting. I'll give it a try!",
                            IsActive = true,
                            RowId = new Guid("c5e6d29a-4391-4889-9dd2-7bd4186ee4fd"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8712),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8713)
                        },
                        new
                        {
                            Id = 40L,
                            Content = "What's your favorite season for outdoor activities?",
                            IsActive = true,
                            RowId = new Guid("c23969cf-b756-4e26-bbc2-7e6575abc960"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8714),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8714)
                        },
                        new
                        {
                            Id = 41L,
                            Content = "I love the fall season. The weather is perfect for hiking.",
                            IsActive = true,
                            RowId = new Guid("fd325630-8ff6-4be0-b697-7c76bce4c02e"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8715),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8717)
                        },
                        new
                        {
                            Id = 42L,
                            Content = "Summer is my favorite. Beach days and outdoor events!",
                            IsActive = true,
                            RowId = new Guid("2c84f4a7-981b-4027-a711-311bcdfbf6ea"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8718),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8718)
                        },
                        new
                        {
                            Id = 43L,
                            Content = "Let's plan a beach day soon.",
                            IsActive = true,
                            RowId = new Guid("aba0fece-8a4e-4df1-a030-c0584af832e5"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8719),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8720)
                        },
                        new
                        {
                            Id = 44L,
                            Content = "I'm in! I miss the sound of ocean waves.",
                            IsActive = true,
                            RowId = new Guid("f179c2cc-d606-4493-a673-d025a12c82ff"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8721),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8721)
                        },
                        new
                        {
                            Id = 45L,
                            Content = "Count me in too! I'll bring the beach games.",
                            IsActive = true,
                            RowId = new Guid("86b534bc-6bf6-4f91-925c-d460611849d9"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8722),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8723)
                        },
                        new
                        {
                            Id = 46L,
                            Content = "Have you ever tried scuba diving?",
                            IsActive = true,
                            RowId = new Guid("7d644dc1-4759-40f5-adad-e7ee020eedac"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8723),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8724)
                        },
                        new
                        {
                            Id = 47L,
                            Content = "Not yet, but it's on my bucket list!",
                            IsActive = true,
                            RowId = new Guid("7bcadb7b-05de-42f4-9aa3-49ef39988c43"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8725),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8726)
                        },
                        new
                        {
                            Id = 48L,
                            Content = "I've been scuba diving in some amazing locations.",
                            IsActive = true,
                            RowId = new Guid("9bf1b33c-b852-4d6c-8b5c-97a99fba534f"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8726),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8727)
                        },
                        new
                        {
                            Id = 49L,
                            Content = "Let's plan a game night with board games and snacks.",
                            IsActive = true,
                            RowId = new Guid("00da277f-1cda-4f8b-9a1f-6c0f64051344"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8728),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8729)
                        },
                        new
                        {
                            Id = 50L,
                            Content = "I'm in! I have a collection of board games at home.",
                            IsActive = true,
                            RowId = new Guid("d60c595a-8596-45bc-b123-cfd66a1cc0d6"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8730),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8731)
                        },
                        new
                        {
                            Id = 51L,
                            Content = "Count me in too! I'll bring some homemade snacks.",
                            IsActive = true,
                            RowId = new Guid("cf0f43ee-6500-43aa-b5fe-14931baaf60d"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8731),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8732)
                        },
                        new
                        {
                            Id = 52L,
                            Content = "Do you have any favorite board games?",
                            IsActive = true,
                            RowId = new Guid("282a29c3-2c71-48e2-978b-fadb55b8d299"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8733),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8733)
                        },
                        new
                        {
                            Id = 53L,
                            Content = "I enjoy strategy games like Settlers of Catan.",
                            IsActive = true,
                            RowId = new Guid("12185111-9683-4431-a026-ce3e487384b0"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8734),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8735)
                        },
                        new
                        {
                            Id = 54L,
                            Content = "I love party games like Codenames. Always so much fun!",
                            IsActive = true,
                            RowId = new Guid("1a40c278-1215-412f-a6c6-974ee3b72c2e"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8736),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8737)
                        },
                        new
                        {
                            Id = 55L,
                            Content = "Let's share our favorite music playlists.",
                            IsActive = true,
                            RowId = new Guid("6889fe03-c794-413d-9633-d4b5f09e65fa"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8738),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8738)
                        },
                        new
                        {
                            Id = 56L,
                            Content = "I'm into indie rock. What about you?",
                            IsActive = true,
                            RowId = new Guid("ef5fef7e-d4cc-4d1f-9d37-452de6cb54ce"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8739),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8740)
                        },
                        new
                        {
                            Id = 57L,
                            Content = "I enjoy a mix of genres, but electronic music is my favorite.",
                            IsActive = true,
                            RowId = new Guid("ba074136-f4ad-4862-ba89-52cc999800ea"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8740),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8742)
                        },
                        new
                        {
                            Id = 58L,
                            Content = "Have you ever attended a music festival?",
                            IsActive = true,
                            RowId = new Guid("21ac5c98-ce6d-4248-8bb6-a344172b4ecd"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8743),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8744)
                        },
                        new
                        {
                            Id = 59L,
                            Content = "Yes, the energy and live performances are unforgettable!",
                            IsActive = true,
                            RowId = new Guid("e156dd9e-785e-49a6-bccc-f2ae5c6fec85"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8744),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8745)
                        },
                        new
                        {
                            Id = 60L,
                            Content = "I've been to a few. It's a unique experience every time.",
                            IsActive = true,
                            RowId = new Guid("916b12e2-ef0f-4127-a523-e4123e86b3ab"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8746),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8746)
                        },
                        new
                        {
                            Id = 61L,
                            Content = "Let's plan a weekend getaway to the mountains.",
                            IsActive = true,
                            RowId = new Guid("53e892f2-a93d-47e8-852f-30b5cdc1b476"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8747),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8748)
                        },
                        new
                        {
                            Id = 62L,
                            Content = "I'm in! A cabin in the woods sounds perfect.",
                            IsActive = true,
                            RowId = new Guid("b25a3fc7-82bd-4552-9673-24570559d8d9"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8748),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8749)
                        },
                        new
                        {
                            Id = 63L,
                            Content = "Count me in too! I love the serenity of the mountains.",
                            IsActive = true,
                            RowId = new Guid("f722109e-16c5-48f3-9be0-42418a6b4f00"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8750),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8750)
                        },
                        new
                        {
                            Id = 64L,
                            Content = "What's your favorite travel destination?",
                            IsActive = true,
                            RowId = new Guid("30a81e4d-69f3-4712-ba6b-aab6d8143b1d"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8751),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8752)
                        },
                        new
                        {
                            Id = 65L,
                            Content = "I love exploring European cities and their rich history.",
                            IsActive = true,
                            RowId = new Guid("d26a3b1e-fddc-4fcc-bfaa-9a58603204f2"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8752),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8754)
                        },
                        new
                        {
                            Id = 66L,
                            Content = "Beach destinations are my favorite. I love the sun and sand.",
                            IsActive = true,
                            RowId = new Guid("57fc0048-3c91-4c67-844f-fb9197d4595f"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8755),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8756)
                        },
                        new
                        {
                            Id = 67L,
                            Content = "Let's plan a photography day and capture the beauty around us.",
                            IsActive = true,
                            RowId = new Guid("99ab3f00-5bc8-4e65-b4fd-31806414e295"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8756),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8757)
                        },
                        new
                        {
                            Id = 68L,
                            Content = "Great idea! I'll bring my camera and some lenses.",
                            IsActive = true,
                            RowId = new Guid("74afec30-68c9-4db8-a020-caa992afbb7a"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8758),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8758)
                        },
                        new
                        {
                            Id = 69L,
                            Content = "Count me in too! I love photography.",
                            IsActive = true,
                            RowId = new Guid("66979b11-f8a3-45c9-8014-2c5725770f63"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8759),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8760)
                        },
                        new
                        {
                            Id = 70L,
                            Content = "Do you prefer digital or film photography?",
                            IsActive = true,
                            RowId = new Guid("b8d6960a-47e6-49f5-b161-a31efea718c8"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8760),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8761)
                        },
                        new
                        {
                            Id = 71L,
                            Content = "I love the convenience of digital photography.",
                            IsActive = true,
                            RowId = new Guid("a77a0717-9064-4857-8e91-a8b9fbd78321"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8762),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8762)
                        },
                        new
                        {
                            Id = 72L,
                            Content = "Film photography has a unique charm. I enjoy both.",
                            IsActive = true,
                            RowId = new Guid("3c110884-1f65-4a79-a997-063a082325c9"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8763),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8764)
                        },
                        new
                        {
                            Id = 73L,
                            Content = "Let's try a new restaurant together. Any cuisine preferences?",
                            IsActive = true,
                            RowId = new Guid("d6efd2fc-9d97-401a-b25f-8a432e16ffdd"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8765),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8766)
                        },
                        new
                        {
                            Id = 74L,
                            Content = "I'm a fan of Italian cuisine. Pasta and pizza are my weaknesses.",
                            IsActive = true,
                            RowId = new Guid("d6b49a41-976c-482a-8914-5def480df4da"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8767),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8768)
                        },
                        new
                        {
                            Id = 75L,
                            Content = "I love exploring different cuisines. Surprise me!",
                            IsActive = true,
                            RowId = new Guid("d686b511-7504-4713-b68e-4ac600fff87c"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8768),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8769)
                        },
                        new
                        {
                            Id = 76L,
                            Content = "Have you ever participated in a charity run or walk?",
                            IsActive = true,
                            RowId = new Guid("05490d53-9653-46f4-9720-91ddcb1e3a81"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8770),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8770)
                        },
                        new
                        {
                            Id = 77L,
                            Content = "Yes, it's a great way to stay active and contribute to a cause.",
                            IsActive = true,
                            RowId = new Guid("5dec091f-74c2-464f-b15d-398117406576"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8771),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8772)
                        },
                        new
                        {
                            Id = 78L,
                            Content = "I've been part of a few. It's fulfilling to make a difference.",
                            IsActive = true,
                            RowId = new Guid("4693cf7e-f8ce-4e7f-b2d0-3ccf18bb50e5"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8772),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8773)
                        },
                        new
                        {
                            Id = 79L,
                            Content = "Let's plan a weekend brunch. Any favorite brunch spots?",
                            IsActive = true,
                            RowId = new Guid("123f1f41-deaa-4f9d-999d-695725c78876"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8774),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8774)
                        },
                        new
                        {
                            Id = 80L,
                            Content = "I know a cozy café with the best brunch menu!",
                            IsActive = true,
                            RowId = new Guid("806195c9-80f7-4d00-8fb1-135e167c4808"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8775),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8776)
                        },
                        new
                        {
                            Id = 81L,
                            Content = "I'm up for brunch! Let's try something new and exciting.",
                            IsActive = true,
                            RowId = new Guid("0404ff56-8e9e-4ecd-8958-c5f1b97c8134"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8776),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8778)
                        },
                        new
                        {
                            Id = 82L,
                            Content = "What's your go-to workout routine?",
                            IsActive = true,
                            RowId = new Guid("20655b6b-ea82-461d-bbf5-c1c170fddf73"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8779),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8779)
                        },
                        new
                        {
                            Id = 83L,
                            Content = "I enjoy a mix of cardio and strength training.",
                            IsActive = true,
                            RowId = new Guid("4f31bbcc-fbed-4fd3-8fb8-09864f9c3904"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8780),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8781)
                        },
                        new
                        {
                            Id = 84L,
                            Content = "Yoga is my go-to. It keeps me balanced and relaxed.",
                            IsActive = true,
                            RowId = new Guid("bd7d1708-09e9-45e3-877c-94cf1d170326"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8781),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8782)
                        },
                        new
                        {
                            Id = 85L,
                            Content = "Let's plan a movie night. Any genre preferences?",
                            IsActive = true,
                            RowId = new Guid("aa095ed4-760d-4a97-9446-57a70c5541c9"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8783),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8783)
                        },
                        new
                        {
                            Id = 86L,
                            Content = "I love sci-fi movies. The more futuristic, the better!",
                            IsActive = true,
                            RowId = new Guid("969473a8-66ee-4a31-ac62-1f141a6eb159"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8784),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8785)
                        },
                        new
                        {
                            Id = 87L,
                            Content = "I enjoy a good comedy. Laughter is the best medicine.",
                            IsActive = true,
                            RowId = new Guid("76caeccd-4ac8-4a47-a23f-525bdcc953bd"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8786),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8786)
                        },
                        new
                        {
                            Id = 88L,
                            Content = "Have you ever tried bungee jumping or skydiving?",
                            IsActive = true,
                            RowId = new Guid("2b16a656-d2d8-48dc-8b61-8a622da177db"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8787),
                            SubGroupId = 1L,
                            UserId = 1L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8787)
                        },
                        new
                        {
                            Id = 89L,
                            Content = "Not yet, but it's on my adventure bucket list!",
                            IsActive = true,
                            RowId = new Guid("018ca5fb-bfa4-4e16-bd09-7a8bb095f63e"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8788),
                            SubGroupId = 1L,
                            UserId = 2L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8790)
                        },
                        new
                        {
                            Id = 90L,
                            Content = "I've tried both. The adrenaline rush is indescribable!",
                            IsActive = true,
                            RowId = new Guid("44f20183-761a-4570-bf77-22e8e8624980"),
                            SentTime = new DateTime(2024, 2, 23, 17, 44, 6, 909, DateTimeKind.Local).AddTicks(8791),
                            SubGroupId = 1L,
                            UserId = 3L,
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8791)
                        });
                });

            modelBuilder.Entity("WebChat.Domain.Entities.SubGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UtcDateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UtcDateModified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("SubGroup");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            GroupId = 1L,
                            IsActive = true,
                            Name = "10 Minute",
                            RowId = new Guid("6eec2292-b40d-4347-b5bb-e41ac9d0c35d"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8891)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            GroupId = 2L,
                            IsActive = true,
                            Name = "10 Minute",
                            RowId = new Guid("4aa404c8-736e-451c-823f-c6710bfe56b9"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8893)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            GroupId = 3L,
                            IsActive = true,
                            Name = "10 Minute",
                            RowId = new Guid("c664928b-0c53-4952-990f-4efef5c12a2c"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8895)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = 1L,
                            GroupId = 4L,
                            IsActive = true,
                            Name = "10 Minute",
                            RowId = new Guid("c01900c4-803c-45a6-a1b6-87d364894a8a"),
                            UtcDateCreated = new DateTime(2024, 2, 23, 13, 44, 6, 909, DateTimeKind.Utc).AddTicks(8896)
                        });
                });

            modelBuilder.Entity("WebChat.Domain.Entities.UserDetailsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("NickName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UtcDateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UtcDateModified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("WebChat.Domain.Entities.GroupUsersEntity", b =>
                {
                    b.HasOne("WebChat.Domain.Entities.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebChat.Domain.Entities.SubGroupEntity", "SubGroup")
                        .WithMany()
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("WebChat.Domain.Entities.MessageEntity", b =>
                {
                    b.HasOne("WebChat.Domain.Entities.SubGroupEntity", "SubGroup")
                        .WithMany()
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("WebChat.Domain.Entities.SubGroupEntity", b =>
                {
                    b.HasOne("WebChat.Domain.Entities.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
