global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using WebChat.Application.ApplicationSettings;
global using UpdateChatUserDetail.WorkerService;
global using System.Reflection;
global using WebChat.Infrastructure.Services.ApplicationInfrastructure;
global using WebChat.Infrastructure.Services.Redis;